### ISSUE TITLE
Typo in example links

### ISSUE THREAD

**Issue by stevenhauser** [fatiherikli/react-designer#1]
Wow this is an incredible project—awesome job! I did notice that your "Show example on github" links are busted though—you have a typo in your `href`s.

**Comment by fatiherikli** [comment]
Hey thanks, I've just fixed all links :+1:

**Comment by stevenhauser** [comment]
Cool. Looks like [Malevich](https://github.com/fatiherikli/react-designer/blob/master/examples/App.js#L83) is still busted though. Sorry, I'd fix it myself but don't want to fork a repo just to fix a typo when it'll take you two seconds!

**Comment by fatiherikli** [comment]
Oups :')

I fixed it too now. Thank you :+1:
