### ISSUE TITLE
Lack of a working version of the project!

### ISSUE THREAD

**Issue by Belka383** [fatiherikli/react-designer#25]
Good afternoon!

But unfortunately, my development team can not use it, because there are some bugs in the project.
We use: node 8.10.0, npm 5.6.0, 
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
and VS Code as a development environment.

I present you the code of a small project (taken from a demo with gitHub) and the errors that have arisen below:
import React, { Component } from 'react'
import logo from './logo.svg'
import './App.css'
import Designer, {Text, Rect} from 'react-designer/src/Designer

class App extends Component {
  state = {
    objects: [
      {type: "text", x: 10, y: 20, text: "Hello!", fill: "red"},
      {type: "rect", x: 50, y: 70, width: 30, height: 40, fill: "red"}
    ]
  }
  render() {
    return (
      `<div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React Designer</h1>`
        </header>
        <Designer width={500} height={500}
          objectTypes={{
            'text': Text,
            'rect': Rect
          }}
          onUpdate={(objects) => this.setState({objects})}
          objects={this.state.objects} 
        />
      </div>
    )
  }
}

export default App

error: 
Failed to compile.

./node_modules/react-designer/src/Designer.js
Module parse failed: Unexpected token (17:22)
You may need an appropriate loader to handle this file type.
|
| class Designer extends Component {
|   static defaultProps = {
|     objectTypes: {
|       'text': Text,

We would like to understand why an error occurs, hope that you will help get rid of it and update the repository! 
I look forward to your comments.

Best regards,
Teterkin Igor

**Comment by fatiherikli** [comment]
hello! could you please check your babel configuration? it should be stage-0

**Comment by Belka383** [comment]
@fatiherikli Here is what is used in the project:
'babel-cli': '^ 6.5.1',
    'babel-core': '^ 6.0.20',
    'babel-eslint': '^ 4.1.3',
    'babel-loader': '^ 6.0.1',
    'babel-plugin-css-modules-transform': '0.0.4',
    'babel-plugin-webpack-loaders': '^ 0.2.1',
    'babel-preset-es2015': '^ 6.0.15',
    'babel-preset-react': '^ 6.24.1',
    'babel-preset-stage-0': '^ 6.24.1',

First I want to run your project, which I can not do at all. Describe the action algorithm after restoring all the packages, please.

For example, if you use the build command, you get the following error in your project after restoring all packages:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-designer@1.0.8 build: `babel -d lib/ src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-designer@1.0.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Belka383** [comment]
@fatiherikli but how to use this module without the babel and webpack?
