### ISSUE TITLE
Missing entry for node module?

### ISSUE THREAD

**Issue by slightlytyler** [fatiherikli/react-designer#5]
After installing and importing I'm getting `Module not found: ERROR: Cannot resolve module from 'react-designer'`. Looking at the package.json I'm seeing `lib/Select.js` as the entry but don't see `lib` directory  included in the module. Am I missing something or is the package broken? Can't wait to try out the library though, looks great!

**Comment by fatiherikli** [comment]
Thank you for the feedback, I'm investigating the issue.

**Comment by slightlytyler** [comment]
@fatiherikli no worries, always happy to help

**Comment by fatiherikli** [comment]
Hey sorry, I had just noticed your pull-request :( I had already fixed that.

**Comment by fatiherikli** [comment]
You can try `npm update react-designer` now.

**Comment by fatiherikli** [comment]
I will also update the examples on the demonstration page.

**Comment by slightlytyler** [comment]
@fatiherikli works now! 🙏

**Comment by raffe90** [comment]
I keep getting `Module not found: ERROR: Cannot resolve module from 'react-designer'`

I'm on 1.0.8
